# Expected: DENY (registry tidak dikenal, bukan registry.gitlab.com)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-s1-04
  namespace: taskflow-prod
spec:
  replicas: 1
  selector:
    matchLabels: {app: test-s1-04}
  template:
    metadata:
      labels: {app: test-s1-04}
    spec:
      containers:
        - name: app
          image: ghcr.io/someone/someapp:v1.0
          resources:
            requests: {cpu: "100m", memory: "128Mi"}
            limits: {cpu: "500m", memory: "256Mi"}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
