# Expected: DENY (CPU limit 10 core, melebihi batas wajar 2000m)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-s3-05
  namespace: taskflow-prod
spec:
  replicas: 1
  selector:
    matchLabels: {app: test-s3-05}
  template:
    metadata:
      labels: {app: test-s3-05}
    spec:
      containers:
        - name: app
          image: registry.gitlab.com/haidarra-devops/week-9-devops-taskflow:sha-abc1234
          resources:
            requests: {cpu: "100m", memory: "128Mi"}
            limits: {cpu: "10000m", memory: "256Mi"}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
