# Expected: DENY (image bukan dari registry.gitlab.com)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-s1-01
  namespace: taskflow-prod
spec:
  replicas: 1
  selector:
    matchLabels: {app: test-s1-01}
  template:
    metadata:
      labels: {app: test-s1-01}
    spec:
      containers:
        - name: app
          image: docker.io/library/nginx:1.25
          resources:
            requests: {cpu: "100m", memory: "128Mi"}
            limits: {cpu: "500m", memory: "256Mi"}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
